/** Shared Tailwind classes per agent role (keep in sync across activity feed + message cards). */
export const agentTheme: Record<string, { color: string; bg: string; border: string; text: string; dot: string; icon: string }> = {
  orchestrator: {
    color: 'text-blue-300',
    bg: 'bg-blue-950/60',
    border: 'border-blue-800/50',
    text: 'text-blue-400',
    dot: 'bg-blue-500',
    icon: '🧠',
  },
  planner: {
    color: 'text-blue-300',
    bg: 'bg-blue-950/60',
    border: 'border-blue-800/50',
    text: 'text-blue-400',
    dot: 'bg-blue-500',
    icon: '📋',
  },
  executor: {
    color: 'text-emerald-300',
    bg: 'bg-emerald-950/60',
    border: 'border-emerald-800/50',
    text: 'text-emerald-400',
    dot: 'bg-emerald-500',
    icon: '⚡',
  },
  auditor: {
    color: 'text-amber-300',
    bg: 'bg-amber-950/60',
    border: 'border-amber-800/50',
    text: 'text-amber-400',
    dot: 'bg-amber-500',
    icon: '🔍',
  },
  'security-auditor': {
    color: 'text-orange-300',
    bg: 'bg-orange-950/60',
    border: 'border-orange-800/50',
    text: 'text-orange-400',
    dot: 'bg-orange-500',
    icon: '🛡',
  },
  'final-reviewer': {
    color: 'text-purple-300',
    bg: 'bg-purple-950/60',
    border: 'border-purple-800/50',
    text: 'text-purple-400',
    dot: 'bg-purple-500',
    icon: '✅',
  },
  router: {
    color: 'text-cyan-300',
    bg: 'bg-cyan-950/60',
    border: 'border-cyan-800/50',
    text: 'text-cyan-400',
    dot: 'bg-cyan-500',
    icon: '🔀',
  },
  memory: {
    color: 'text-zinc-300',
    bg: 'bg-zinc-800/60',
    border: 'border-zinc-700/50',
    text: 'text-zinc-400',
    dot: 'bg-zinc-500',
    icon: '💾',
  },
  evaluator: {
    color: 'text-fuchsia-300',
    bg: 'bg-fuchsia-950/60',
    border: 'border-fuchsia-800/50',
    text: 'text-fuchsia-400',
    dot: 'bg-fuchsia-500',
    icon: '🧪',
  },
  tools: {
    color: 'text-sky-300',
    bg: 'bg-sky-950/50',
    border: 'border-sky-800/50',
    text: 'text-sky-400',
    dot: 'bg-sky-500',
    icon: '🔧',
  },
  system: {
    color: 'text-zinc-400',
    bg: 'bg-zinc-800/40',
    border: 'border-zinc-700/40',
    text: 'text-zinc-500',
    dot: 'bg-zinc-600',
    icon: '⚙',
  },
}

export function themeForAgent(agent: string) {
  return agentTheme[agent] ?? agentTheme.system
}
