name: PHP Tests

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  phpunit:
    name: Laravel PHPUnit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo_sqlite, redis
          coverage: none

      - name: Install dependencies
        working-directory: app
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        working-directory: app
        run: php artisan test
